version: 2
jobs: 
  build:
    docker:
      - image: buildpack-deps:trusty 
    steps:
      - run:
          name: wget docker-compose 
          command: |
                   VER="17.03.0-ce" 
                   curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz 
                   tar -xz -C /tmp -f /tmp/docker-$VER.tgz 
                   mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: test      
          command: |
                   docker
      - run:
          name: test
          command: |
                   echo fun


workflows:
  version: 2
  all:
    jobs:
      - build:
          requires:
            - hold
      - hold:
          type: approval         

